nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - arm64
    - ia32
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
    - win32
