name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - "main"
jobs:
  build-deploy-storybook:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Build Storybook'
        shell: bash
        run: |
          cd frontend
          yarn set version stable
          yarn install
          yarn build-storybook
      - name: 'Upload storybook artifact'
        uses: actions/upload-pages-artifact@v2
        with: 
          path: ${{ github.workspace }}/frontend/storybook-static
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
